services:
  redis:
    image: redis:7-alpine
    volumes:
      - datos_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  datos_redis:
    driver: local
