services:
  redis:
    image: redis:7-alpine
    volumes:
      - datos_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./app
    image: majorodri/devunlocked-web:v1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    image: majorodri/devunlocked-nginx:v1
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  datos_redis:
    driver: local
